# Generated by Django 5.2.1 on 2025-06-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iamge',
            new_name='image',
        ),
    ]
