# Generated by Django 5.2.1 on 2025-06-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_iamge_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='img',
        ),
    ]
